// Copyright © 2025 Constantinos Vidiniotis. All rights reserved.
// Licensed under Elastic License 2.0 - see LICENSE.md for details.
//
// One example event per name in the LoopEvent union - used by the
// dev-route ``/app/dev/reasoning-tape`` so a designer can eyeball
// every renderer without a live agent run, and as the source of
// truth for any future Storybook/RTL fixtures.

import type { LoopEvent } from '@/lib/loopEvents'

const T = 1717070000 // arbitrary fixed Unix epoch for deterministic UI snapshots

export const FIXTURE_RUN_ID = 'fixture-run'

export const LOOP_EVENT_FIXTURES: LoopEvent[] = [
  {
    event: 'loop.opened',
    ts: T + 1,
    run_id: FIXTURE_RUN_ID,
    session_id: 'sess-fixture',
    query: 'Draft the FRIA for our high-risk hiring scoring model.',
    model: 'gpt-4o-mini',
  },
  {
    event: 'loop.triage',
    ts: T + 2,
    run_id: FIXTURE_RUN_ID,
    complexity: 'comprehensive',
    intent: 'draft_fria',
    confidence: 0.82,
    lane: 'slow',
    reasoning: 'High-risk Annex III row 4 system - full FRIA recipe required.',
  },
  {
    event: 'loop.cache.miss',
    ts: T + 3,
    run_id: FIXTURE_RUN_ID,
    key_kind: 'semantic',
    lookup_ms: 14.2,
  },
  {
    event: 'loop.plan',
    ts: T + 4,
    run_id: FIXTURE_RUN_ID,
    steps: [
      { id: 's1', intent: 'classify_ai_act_risk', tool_hint: 'classify_ai_act_risk' },
      { id: 's2', intent: 'recall existing facts', tool_hint: 'recall_facts' },
      { id: 's3', intent: 'execute FRIA recipe', tool_hint: 'run_recipe' },
    ],
  },
  {
    event: 'loop.step.start',
    ts: T + 5,
    run_id: FIXTURE_RUN_ID,
    step_id: 's1',
    intent: 'classify_ai_act_risk',
  },
  {
    event: 'loop.thought.delta',
    ts: T + 6,
    run_id: FIXTURE_RUN_ID,
    step_id: 's1',
    text: 'Hiring scoring is Annex III row 4 - high-risk by definition.',
  },
  {
    event: 'loop.tool.call',
    ts: T + 7,
    run_id: FIXTURE_RUN_ID,
    step_id: 's1',
    tool: 'classify_ai_act_risk',
    args: { description: 'AI scoring of job applicants' },
  },
  {
    event: 'loop.tool.result',
    ts: T + 8,
    run_id: FIXTURE_RUN_ID,
    step_id: 's1',
    tool: 'classify_ai_act_risk',
    summary: 'high-risk · Annex III row 4 (employment, recruitment)',
    citations: [{ ref: 'eu_ai_act_annex_iii_row_4' }],
  },
  {
    event: 'loop.ckf.query',
    ts: T + 9,
    run_id: FIXTURE_RUN_ID,
    mode: 'recall_facts',
    scope: 'tenant',
    hits: 3,
    top_confidence: 0.91,
  },
  {
    event: 'loop.web.start',
    ts: T + 10,
    run_id: FIXTURE_RUN_ID,
    query: 'EU AI Act Article 27 fundamental rights impact assessment template',
    backend: 'local',
    profile: 'crp_comply_official',
    freshness: 'month',
  },
  {
    event: 'loop.web.result',
    ts: T + 11,
    run_id: FIXTURE_RUN_ID,
    backend: 'local',
    hits: [
      {
        domain: 'eur-lex.europa.eu',
        trust_tier: 1,
        url: 'https://eur-lex.europa.eu/...',
        title: 'EU AI Act - Article 27',
      },
      {
        domain: 'edpb.europa.eu',
        trust_tier: 1,
        url: 'https://edpb.europa.eu/...',
        title: 'EDPB guidance on FRIA',
      },
      {
        domain: 'iso.org',
        trust_tier: 2,
        url: 'https://iso.org/...',
        title: 'ISO/IEC 42001 - alignment',
      },
      {
        domain: 'medium.com',
        trust_tier: 4,
        title: '(blocked: low-trust source)',
        blocked: true,
      },
    ],
    blocked: 1,
    latency_ms: 412.3,
    quota_remaining: 998,
  },
  {
    event: 'loop.cache.hit',
    ts: T + 12,
    run_id: FIXTURE_RUN_ID,
    key_kind: 'plan',
    similarity: 0.93,
    age_seconds: 187,
    citations: [{ ref: 'eu_ai_act_art_27' }, { ref: 'eu_ai_act_annex_iii_row_4' }],
  },
  {
    event: 'loop.reflection',
    ts: T + 13,
    run_id: FIXTURE_RUN_ID,
    step_id: 's1',
    verdict: 'ok',
    notes: 'Risk classification complete; proceed to recipe.',
  },
  {
    event: 'loop.clarifier.ask',
    ts: T + 14,
    run_id: FIXTURE_RUN_ID,
    step_id: 's3',
    question: 'How many candidates does the system score per month?',
    slot_id: 'monthly_volume',
    options: ['<1k', '1k–10k', '10k–100k', '>100k'],
    resume_token: 'rt-fixture',
  },
  {
    event: 'loop.clarifier.answer',
    ts: T + 15,
    run_id: FIXTURE_RUN_ID,
    slot_id: 'monthly_volume',
    answer: '10k–100k',
  },
  {
    event: 'loop.step.end',
    ts: T + 16,
    run_id: FIXTURE_RUN_ID,
    step_id: 's1',
    status: 'ok',
  },
  {
    event: 'loop.recipe.start',
    ts: T + 17,
    run_id: FIXTURE_RUN_ID,
    recipe_id: 'eu_ai_act_art_27_fria',
    inputs: { system_name: 'HireScore', data_subjects: 'job applicants' },
  },
  {
    event: 'loop.recipe.delta',
    ts: T + 18,
    run_id: FIXTURE_RUN_ID,
    recipe_id: 'eu_ai_act_art_27_fria',
    kind: 'section',
    text: "section 'Purpose' drafted (3 para, 2 citations)",
  },
  {
    event: 'loop.recipe.delta',
    ts: T + 19,
    run_id: FIXTURE_RUN_ID,
    recipe_id: 'eu_ai_act_art_27_fria',
    kind: 'section',
    text: "section 'Affected persons' drafted (4 para, 3 citations)",
  },
  {
    event: 'loop.recipe.done',
    ts: T + 20,
    run_id: FIXTURE_RUN_ID,
    recipe_id: 'eu_ai_act_art_27_fria',
    artefact_id: 'rep-fixture-1',
  },
  {
    event: 'loop.heartbeat',
    ts: T + 21,
    run_id: FIXTURE_RUN_ID,
    state: 'finalising',
  },
  {
    event: 'loop.error',
    ts: T + 22,
    run_id: FIXTURE_RUN_ID,
    message: 'notifier failed: SMTP timeout (non-fatal)',
    step_id: 's3',
  },
  {
    event: 'loop.final',
    ts: T + 23,
    run_id: FIXTURE_RUN_ID,
    summary: 'FRIA produced and stored as report rep-fixture-1.',
    artefacts: [{ id: 'rep-fixture-1', kind: 'fria' }],
    total_steps: 3,
  },
  {
    event: 'loop.abort',
    ts: T + 24,
    run_id: FIXTURE_RUN_ID,
    reason: 'budget_exceeded',
    dimension: 'wall_clock',
    limit: 300,
    usage: 312.4,
    budget: {
      max_steps: 12,
      max_tokens: 60000,
      max_wall_clock_s: 300,
      max_clarifiers: 6,
      max_plan_revisions: 3,
    },
    totals: {
      steps: 9,
      tokens: 41200,
      wall_clock_s: 312.4,
      clarifiers: 1,
      plan_revisions: 0,
    },
  },
]
