# Copyright © 2025-2026 Constantinos Vidiniotis / AutoCyber AI Pty Ltd.
# Licensed under Elastic License 2.0 — see LICENSE.md for details.
"""Persisted deliverables store — compliance reports and evidence packs.

Every report generated by the compliance endpoints (risk-assessment, DPIA,
transparency, technical-docs, compliance-report, session-audit, full-report,
evidence-pack) is written to disk so it can be listed, re-downloaded, and
handed back to users in case of client-side loss or dispute.

Layout on the persistent volume::

    /app/data/reports/
        index.json                     # global index (user_id -> [report_ids])
        {user_id}/
            {report_id}.json           # metadata + payload

    /app/data/evidence_packs/
        {user_id}/
            {pack_id}/
                manifest.json
                risk_assessment.json
                dpia.md
                transparency.md
                technical_docs.md
                compliance_report.md
                audit_chain.json
                evidence_pack.zip      # all of the above bundled

Reports are small JSON blobs; zip packs may be several MB. Retention is managed
by the background task in :mod:`crp_comply.api.app`.
"""

from __future__ import annotations

import json
import logging
import threading
import uuid
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal

logger = logging.getLogger("crp_comply.api.reports")

ReportKind = Literal[
    "risk_assessment",
    "compliance_report",
    "compliance_report_markdown",
    "dpia",
    "transparency",
    "technical_docs",
    "session_audit",
    "full_report",
    "evidence_pack",
    "agent_session",
    "recipe_run",
]

_REPORT_KINDS: set[str] = {
    "risk_assessment",
    "compliance_report",
    "compliance_report_markdown",
    "dpia",
    "transparency",
    "technical_docs",
    "session_audit",
    "full_report",
    "evidence_pack",
    "agent_session",
    "recipe_run",
}


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _sanitize(user_id: str) -> str:
    """Make a user id filesystem-safe."""
    keep = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_."
    return "".join(c if c in keep else "_" for c in user_id)[:128] or "anonymous"


def _normalise_provenance(prov: dict[str, Any]) -> dict[str, Any]:
    """Normalise a caller-supplied provenance dict and hash every input.

    Accepted keys:
      - ``corpus_manifest``: dict or path to corpus/_scraped/manifest.json.
        Persisted verbatim alongside a sha256 of its canonical JSON.
      - ``corpus_manifest_hash``: pre-computed sha256 (optional; recomputed
        if ``corpus_manifest`` is also provided).
      - ``ckf_fact_ids`` / ``ckf_event_ids``: lists of reference ids whose
        CKF payloads support the verdicts in the pack.
      - ``verdict_rules``: optional list of ``{clause, rule, inputs}``
        records capturing which predicates were evaluated.
    """
    import hashlib as _hashlib

    out: dict[str, Any] = {}
    cm = prov.get("corpus_manifest")
    if isinstance(cm, (str, Path)):
        try:
            cm_text = Path(cm).read_text(encoding="utf-8")
            out["corpus_manifest"] = json.loads(cm_text)
            out["corpus_manifest_hash"] = _hashlib.sha256(cm_text.encode("utf-8")).hexdigest()
        except Exception as exc:
            out["corpus_manifest_error"] = f"could not load: {exc}"
    elif isinstance(cm, dict):
        canon = json.dumps(cm, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")
        out["corpus_manifest"] = cm
        out["corpus_manifest_hash"] = _hashlib.sha256(canon).hexdigest()

    if "corpus_manifest_hash" in prov and "corpus_manifest_hash" not in out:
        out["corpus_manifest_hash"] = str(prov["corpus_manifest_hash"])

    for key in ("ckf_fact_ids", "ckf_event_ids"):
        vals = prov.get(key)
        if isinstance(vals, (list, tuple)) and vals:
            out[key] = [str(v) for v in vals]

    vr = prov.get("verdict_rules")
    if isinstance(vr, list) and vr:
        out["verdict_rules"] = vr

    return out


class ReportStore:
    """Thread-safe JSON-backed store for generated deliverables.

    Reports are persisted under ``reports/{user_id}/{report_id}.json`` with
    structure::

        {
            "id": "...",
            "user_id": "...",
            "kind": "dpia",
            "system_name": "...",
            "risk_level": "HIGH",
            "tier": "pro",
            "created_at": "2026-04-22T...",
            "size_bytes": 4215,
            "payload": { ... actual report ... },
            "markdown": "..."   # optional, for markdown-flavoured reports
        }

    Plus a tiny per-user index file for fast listing.
    """

    def __init__(self, data_dir: Path) -> None:
        self._root = Path(data_dir) / "reports"
        self._root.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()

    # ── user scoped paths ──────────────────────────────────────
    def _user_dir(self, user_id: str) -> Path:
        d = self._root / _sanitize(user_id)
        d.mkdir(parents=True, exist_ok=True)
        return d

    def _record_path(self, user_id: str, report_id: str) -> Path:
        safe_id = _sanitize(report_id)
        return self._user_dir(user_id) / f"{safe_id}.json"

    # ── write ──────────────────────────────────────────────────
    def save(
        self,
        *,
        user_id: str,
        kind: str,
        system_name: str,
        tier: str,
        payload: dict[str, Any],
        markdown: str | None = None,
        risk_level: str | None = None,
        derivation: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Persist a report and return the metadata envelope."""
        if kind not in _REPORT_KINDS:
            raise ValueError(f"Unknown report kind: {kind}")

        report_id = str(uuid.uuid4())
        now = _utc_now_iso()

        record: dict[str, Any] = {
            "id": report_id,
            "user_id": user_id,
            "kind": kind,
            "system_name": system_name or "unspecified",
            "risk_level": risk_level,
            "tier": tier,
            "created_at": now,
            "payload": payload,
        }
        if markdown is not None:
            record["markdown"] = markdown
        # Derivation manifest (Gap #7) — empty dict means "not tracked",
        # which short-circuits staleness detection so legacy reports
        # don't suddenly start reporting "stale" with no basis.
        if derivation:
            record["derivation"] = derivation

        path = self._record_path(user_id, report_id)
        with self._lock:
            blob = json.dumps(record, indent=2, default=str, ensure_ascii=False)
            path.write_text(blob, encoding="utf-8")
            record["size_bytes"] = len(blob.encode("utf-8"))

        logger.info(
            "report saved: kind=%s id=%s user=%s system=%s bytes=%d",
            kind,
            report_id,
            user_id,
            system_name,
            record["size_bytes"],
        )
        return record

    # ── read ───────────────────────────────────────────────────
    def get(self, user_id: str, report_id: str) -> dict[str, Any] | None:
        path = self._record_path(user_id, report_id)
        if not path.exists():
            return None
        try:
            rec = json.loads(path.read_text(encoding="utf-8"))
            rec["size_bytes"] = path.stat().st_size
            return rec
        except Exception as exc:
            logger.warning("failed to read report %s: %s", path, exc)
            return None

    def list(
        self,
        user_id: str,
        *,
        kind: str | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> list[dict[str, Any]]:
        """Return metadata envelopes (without payloads) for a user."""
        d = self._user_dir(user_id)
        items: list[dict[str, Any]] = []
        for path in d.glob("*.json"):
            try:
                rec = json.loads(path.read_text(encoding="utf-8"))
            except Exception as _bandit_exc:
                logger.debug("swallowed in reports.list_reports: %s", _bandit_exc)
                continue
            if kind and rec.get("kind") != kind:
                continue
            items.append(
                {
                    "id": rec.get("id"),
                    "kind": rec.get("kind"),
                    "system_name": rec.get("system_name"),
                    "risk_level": rec.get("risk_level"),
                    "tier": rec.get("tier"),
                    "created_at": rec.get("created_at"),
                    "size_bytes": path.stat().st_size,
                    "has_markdown": "markdown" in rec,
                }
            )

        items.sort(key=lambda r: r.get("created_at") or "", reverse=True)
        return items[offset : offset + limit]

    def count(self, user_id: str) -> dict[str, int]:
        """Return per-kind counts + total + total_bytes."""
        d = self._user_dir(user_id)
        counts: dict[str, int] = {}
        total_bytes = 0
        total = 0
        for path in d.glob("*.json"):
            try:
                rec = json.loads(path.read_text(encoding="utf-8"))
            except Exception as _bandit_exc:
                logger.debug("swallowed in reports.counts: %s", _bandit_exc)
                continue
            k = rec.get("kind", "unknown")
            counts[k] = counts.get(k, 0) + 1
            total_bytes += path.stat().st_size
            total += 1
        counts["_total"] = total
        counts["_total_bytes"] = total_bytes
        return counts

    def delete(self, user_id: str, report_id: str) -> bool:
        path = self._record_path(user_id, report_id)
        if not path.exists():
            return False
        try:
            path.unlink()
            return True
        except Exception as exc:
            logger.warning("failed to delete report %s: %s", path, exc)
            return False

    def purge_older_than(self, *, days: int) -> int:
        """Delete all reports older than N days across all users."""
        cutoff = datetime.now(timezone.utc).timestamp() - (days * 86400)
        removed = 0
        for user_dir in self._root.iterdir():
            if not user_dir.is_dir():
                continue
            for path in user_dir.glob("*.json"):
                try:
                    if path.stat().st_mtime < cutoff:
                        path.unlink()
                        removed += 1
                except Exception as _bandit_exc:
                    logger.debug("swallowed in reports.purge_older_than: %s", _bandit_exc)
                    continue
        return removed


# ── Evidence Pack Builder ──────────────────────────────────────

_PACK_FILES = {
    "risk_assessment": "risk_assessment.json",
    "compliance_report": "compliance_report.json",
    "dpia": "dpia.json",
    "transparency": "transparency.json",
    "technical_docs": "technical_docs.json",
    "session_audit": "session_audit.json",
    "full_report_markdown": "compliance_report.md",
}


class EvidencePackBuilder:
    """Build a regulator-ready ZIP containing every compliance artifact.

    The zip is self-contained: any regulator can unzip it offline and inspect
    every artifact without needing access to the live system. Every file has a
    SHA-256 hash in ``manifest.json`` and the manifest itself is signed with
    Ed25519 so third-party tampering is detectable without any shared secret.
    """

    def __init__(self, data_dir: Path) -> None:
        self._root = Path(data_dir) / "evidence_packs"
        self._root.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()

    def _pack_dir(self, user_id: str, pack_id: str) -> Path:
        d = self._root / _sanitize(user_id) / _sanitize(pack_id)
        d.mkdir(parents=True, exist_ok=True)
        return d

    def build(
        self,
        *,
        user_id: str,
        system_name: str,
        category: str,
        tier: str,
        artifacts: dict[str, Any],
        provenance: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Assemble and persist an evidence pack.

        ``artifacts`` is a dict mapping artifact name to the payload dict or
        markdown string. Unknown names are dropped silently; the manifest
        records only what was actually included.

        ``provenance`` optionally carries the corpus manifest snapshot
        (``corpus_manifest``) and CKF reference ids (``ckf_fact_ids``,
        ``ckf_event_ids``) so regulators can re-derive the verdicts.
        All provenance fields are hashed into the manifest signature, so
        tampering is detectable.
        """
        import hashlib

        pack_id = str(uuid.uuid4())
        now = _utc_now_iso()
        pack_dir = self._pack_dir(user_id, pack_id)

        manifest: dict[str, Any] = {
            "pack_id": pack_id,
            "user_id": user_id,
            "system_name": system_name,
            "category": category,
            "tier": tier,
            "created_at": now,
            "crp_comply_version": _get_version(),
            "files": [],
        }

        # Attach signed provenance (corpus snapshot + CKF refs) so the
        # audit trail is verifiable end-to-end. (DESIGN_GAP §3.3
        # "signed provenance in evidence pack".)
        if provenance:
            manifest["provenance"] = _normalise_provenance(provenance)

        written: list[tuple[str, bytes]] = []

        for key, payload in artifacts.items():
            filename = _PACK_FILES.get(key)
            if not filename:
                continue
            if isinstance(payload, str):
                data = payload.encode("utf-8")
            else:
                data = json.dumps(payload, indent=2, default=str, ensure_ascii=False).encode(
                    "utf-8"
                )

            sha = hashlib.sha256(data).hexdigest()

            out_path = pack_dir / filename
            out_path.write_bytes(data)
            written.append((filename, data))
            manifest["files"].append(
                {
                    "name": filename,
                    "kind": key,
                    "size_bytes": len(data),
                    "sha256": sha,
                }
            )

        # README for the regulator
        readme = _build_readme(manifest)
        (pack_dir / "README.txt").write_bytes(readme.encode("utf-8"))
        written.append(("README.txt", readme.encode("utf-8")))
        manifest["files"].append(
            {
                "name": "README.txt",
                "kind": "readme",
                "size_bytes": len(readme.encode("utf-8")),
                "sha256": hashlib.sha256(readme.encode("utf-8")).hexdigest(),
            }
        )

        manifest_json = json.dumps(manifest, indent=2, default=str, ensure_ascii=False)
        (pack_dir / "manifest.json").write_text(manifest_json, encoding="utf-8")

        # ── Detached Ed25519 signature over the manifest ──
        # Addresses PRODUCT_SECURITY.md §4 gap #4. Regulators can verify
        # with our published public key (/.well-known/crp-comply-evidence-key.pub)
        # so no shared secret is required for third-party validation.
        try:
            from . import evidence_signing as _es

            key = _es.load_or_create_keys(self._root)
            sig = _es.sign(manifest_json.encode("utf-8"), key)
            manifest["signature"] = {
                "algorithm": sig.algorithm,
                "signature_b64": sig.signature_b64,
                "public_key_b64": sig.public_key_b64,
                "key_fingerprint": sig.key_fingerprint,
                "signed_at": sig.signed_at,
            }
            manifest_json = json.dumps(manifest, indent=2, default=str, ensure_ascii=False)
            (pack_dir / "manifest.json").write_text(manifest_json, encoding="utf-8")
            (pack_dir / "manifest.sig").write_text(sig.signature_b64, encoding="utf-8")
        except Exception as exc:
            logger.warning("evidence signing failed (pack=%s): %s", pack_id, exc)

        # Build the zip
        zip_path = pack_dir / "evidence_pack.zip"
        with self._lock:
            with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as z:
                z.writestr("manifest.json", manifest_json)
                if "signature" in manifest:
                    z.writestr("manifest.sig", manifest["signature"]["signature_b64"])
                for name, data in written:
                    z.writestr(name, data)

        manifest["zip_bytes"] = zip_path.stat().st_size
        manifest["zip_path"] = str(zip_path)
        return manifest

    def get_zip(self, user_id: str, pack_id: str) -> Path | None:
        p = self._pack_dir(user_id, pack_id) / "evidence_pack.zip"
        return p if p.exists() else None

    def get_manifest(self, user_id: str, pack_id: str) -> dict[str, Any] | None:
        p = self._pack_dir(user_id, pack_id) / "manifest.json"
        if not p.exists():
            return None
        try:
            return json.loads(p.read_text(encoding="utf-8"))
        except Exception:
            return None

    def list(self, user_id: str, *, limit: int = 50) -> list[dict[str, Any]]:
        user_root = self._root / _sanitize(user_id)
        if not user_root.exists():
            return []
        packs: list[dict[str, Any]] = []
        for pack_dir in user_root.iterdir():
            if not pack_dir.is_dir():
                continue
            manifest_path = pack_dir / "manifest.json"
            zip_path = pack_dir / "evidence_pack.zip"
            if not manifest_path.exists():
                continue
            try:
                m = json.loads(manifest_path.read_text(encoding="utf-8"))
            except Exception as _bandit_exc:
                logger.debug("swallowed in reports.list_packs: %s", _bandit_exc)
                continue
            packs.append(
                {
                    "pack_id": m.get("pack_id"),
                    "system_name": m.get("system_name"),
                    "category": m.get("category"),
                    "tier": m.get("tier"),
                    "created_at": m.get("created_at"),
                    "file_count": len(m.get("files", [])),
                    "zip_bytes": zip_path.stat().st_size if zip_path.exists() else 0,
                }
            )
        packs.sort(key=lambda p: p.get("created_at") or "", reverse=True)
        return packs[:limit]

    def delete(self, user_id: str, pack_id: str) -> bool:
        d = self._pack_dir(user_id, pack_id)
        if not d.exists():
            return False
        try:
            for p in d.iterdir():
                p.unlink()
            d.rmdir()
            return True
        except Exception as exc:
            logger.warning("failed to delete pack %s: %s", d, exc)
            return False

    def purge_older_than(self, *, days: int) -> int:
        cutoff = datetime.now(timezone.utc).timestamp() - (days * 86400)
        removed = 0
        if not self._root.exists():
            return 0
        for user_dir in self._root.iterdir():
            if not user_dir.is_dir():
                continue
            for pack_dir in user_dir.iterdir():
                if not pack_dir.is_dir():
                    continue
                try:
                    if pack_dir.stat().st_mtime < cutoff:
                        for p in pack_dir.iterdir():
                            p.unlink()
                        pack_dir.rmdir()
                        removed += 1
                except Exception as _bandit_exc:
                    logger.debug("swallowed in reports.purge_packs_older_than: %s", _bandit_exc)
                    continue
        return removed


def _build_readme(manifest: dict[str, Any]) -> str:
    lines = [
        "CRP COMPLY — EVIDENCE PACK",
        "=" * 70,
        "",
        f"Pack ID:       {manifest.get('pack_id')}",
        f"System:        {manifest.get('system_name')}",
        f"Category:      {manifest.get('category')}",
        f"Generated at:  {manifest.get('created_at')}",
        f"CRP Comply:    {manifest.get('crp_comply_version')}",
        "",
        "Purpose",
        "-------",
        "This archive is a regulator-ready evidence pack for the AI system above.",
        "It contains every compliance artifact generated by CRP Comply for this",
        "system: risk classification (EU AI Act Art. 6), DPIA (GDPR Art. 35),",
        "transparency declaration (AI Act Art. 13), technical documentation",
        "(AI Act Art. 11), and a live compliance report.",
        "",
        "Integrity",
        "---------",
        "Every file in this archive has a SHA-256 hash recorded in manifest.json.",
        "The manifest itself is signed with Ed25519; the detached signature is",
        "stored in manifest.sig and the public key is published at",
        "/.well-known/crp-comply-evidence-key.pub.",
        "",
        "Contents",
        "--------",
    ]
    for f in manifest.get("files", []):
        lines.append(f"  {f.get('name'):<32} {f.get('size_bytes'):>8} bytes   [{f.get('kind')}]")
    lines.extend(
        [
            "",
            "Verification",
            "------------",
            "To verify integrity:",
            "  1. Extract this zip.",
            "  2. For each file listed in manifest.json, compute SHA-256 locally.",
            "  3. Compare with manifest's `sha256` field.",
            "  4. Verify the Ed25519 signature in manifest.sig against the published",
            "     public key (/.well-known/crp-comply-evidence-key.pub).",
            "",
            "Questions? support@crp-comply.com",
            "",
        ]
    )
    return "\n".join(lines)


def _get_version() -> str:
    try:
        from crp_comply import __version__

        return __version__
    except Exception:
        return "unknown"


# ── Singletons ─────────────────────────────────────────────────

_store: ReportStore | None = None
_pack_builder: EvidencePackBuilder | None = None


def init_report_store(data_dir: Path) -> None:
    global _store, _pack_builder
    _store = ReportStore(data_dir)
    _pack_builder = EvidencePackBuilder(data_dir)
    logger.info("ReportStore + EvidencePackBuilder initialised at %s", data_dir)


def get_report_store() -> ReportStore:
    if _store is None:
        raise RuntimeError("ReportStore not initialised")
    return _store


def get_pack_builder() -> EvidencePackBuilder:
    if _pack_builder is None:
        raise RuntimeError("EvidencePackBuilder not initialised")
    return _pack_builder
